### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by huerlisi** [nfroidure/SVGPathData#12]
First up: big thanks for your work on this package!

I had some issues with some specific SVGs that seem to be fixed in current master (related to #8).

Would be create if you could release a new version to npm so we can switch to using a released version:-)

**Comment by nfroidure** [comment]
Hi. I just added you as a collaborator, feel free to do it if you need to get it quickly. Leave me your npm username if you also want to be able to publish it.

**Comment by huerlisi** [comment]
@nfroidure nice!

npm name is `huerlisi` too:-)

**Comment by nfroidure** [comment]
Done

**Comment by huerlisi** [comment]
I pushed two small cleanup PRs. Maybe you could quickly review and merge them.

I checked the git logs and it looks like the next release should be a patch release, or do you know of some feature or breaking changes?

I would then do a version bump commit, tag and then release to npm, right?

**Comment by nfroidure** [comment]
I merged them. Thank you.

I think a patch should be fine.

I use npm version to create new version tags. You'll just have to do:
```
npm version patch
npm publish
```

Thanks again for your help.

**Comment by huerlisi** [comment]
Released 1.0.4:-)
