### ISSUE TITLE
Dist build?

### ISSUE THREAD

**Issue by Jolg42** [nfroidure/SVGPathData#16]
Hi,

I just found the 1.04 update but it looks like the [dist file](https://github.com/nfroidure/SVGPathData/blob/master/dist/SVGPathData.js) was not updated since October 2015 and it's not npm neither. Is it on purpose?

Thank you ;)

**Comment by nfroidure** [comment]
It is a mistake, i should have automated it with an npm preversion script.

**Comment by Jolg42** [comment]
@nfroidure No problem 😉
By the way it looks like the prepublish process was updated for npm 4 if you use it! http://iamakulov.com/notes/all/npm-4-prepublish/

```
npm 4 is splitting the prepublish script into two new: prepare and prepublishOnly.

prepare will have the same behavior that prepublish has now. Commands in this script will run both before publishing and on npm install.
prepublishOnly, as seen from its name, will run only before publishing the package.
Also, prepublish will receive a warning about the changes

Decide based on what your package needs.

If your package’s prepublish script contains commands that should only be run before npm publish, rename the script into prepublishOnly. Examples of such commands are npm test and eslint.
If your package’s prepublish script contains commands that should run both before npm publish and on npm install, rename the script to prepare. Examples of such commands are commands that build your package (e. g. webpack or babel).
If you don’t know, rename the script to prepublishOnly – this is the behavior most people expect. (As another option, you can leave everything as-is, but there’s no point: it will just delay the decision, but not remove it.)
```

**Comment by NaridaL** [comment]
package.json: "build": "browserify src/SVGPathData.js -o dist/SVGPathData.js -s SVGPathData",

The build script is shadowed by an internal "npm build" command. See https://stackoverflow.com/questions/29939697/npm-build-doesnt-run-the-script-named-build-in-package-json

I'm guessing this is not the intention...

**Comment by NaridaL** [comment]
Updated the browserify-ed version both in the npm repository and here. Added npm run build to prepublish script. https://github.com/nfroidure/SVGPathData/commit/6c0368a53f8a338080f8b681b8c09ae18fd8d694
