### ISSUE TITLE
Normalization and Sanitation Transformers

### ISSUE THREAD

**Issue by NaridaL** [nfroidure/SVGPathData#18]
Normalization and sanitation transformers would be useful for following operations.

A normalization transformer would transform H, V and Z commands to L commands. Arcs with rx = 0 or ry = 0 could also be included (these are defined as straight lines)
Transforming quadratic to cubic beziers could also be included or as a separate transformer.

A sanitation transformer would remove zero-length segments.

**Comment by nfroidure** [comment]
Agreed, would definitely merge PRs allowing to do so.

**Comment by NaridaL** [comment]
Sanitation transformer is missing 0 length elliptical arcs as those are a bit more complicated. It might benefit from a transformer which adds center position information to the commands.

**Comment by NaridaL** [comment]
Added 0-length arcs to the sanitization transformer (I was overthinking it, checking that the large arc flag is off is enough).

Added QT_TO_C transformer for quad to cubic conversion.
