### ISSUE TITLE
ySimetry on arcs commands

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/SVGPathData#24]
See https://github.com/nfroidure/svgicons2svgfont/issues/57#issuecomment-296124695

**Comment by NaridaL** [comment]
The issue doesn't seem to be here...
Taking the first path in the original issue, the one with the arcs; the result of `new SVGPathData(bad).encode() + new SVGPathData(bad).ySymmetry(30).encode()` is https://jsfiddle.net/ee156twj/, which looks fine.

**Comment by nfroidure** [comment]
Thanks @NaridaL ! I guess they just have to update SVGPathData version, closing then.

**Comment by NaridaL** [comment]
TBH, I'm not sure that will help, I haven't touched the arc code.
